### ISSUE TITLE
NR4: System services should work at any given time with full functionality. 

### ISSUE THREAD

**Issue by McLow27** [WSU-4110/Dinners-Done#27]
|NR4: System services should work at any given time with full functionality. |
|---|
|**Goal**: To be able to access recipes the user wants at any time 
**Stakeholders:** User|
| **Description:**  The users will be able to access any recipe on the site database, favorites list, or personally added recipes at any time. The user will also be able to save and print recipes at any time.   |
| **Origin:** Based on the first project presentation and after discussing customary website criteria during group meetings in week of 5/22, group members agreed to add this requirement.|
| **Version:** 1.0  |
|**Date:** 05/22/2022
|  **Priority:** 4 |

**Comment by KKarnick** [comment]
Prior to the last week, this was an ongoing requirement. The front-end work was assuring code on the HTML pages. The backend workers verified all code was functional on the backend. 
However after majority vote to change the project structure in the last week of the term, there remained a major component that was still not functioning properly. Because of the change to use of a NoSql database (originally MySql which disallows such issues), the Recipe Entry Page is not functioning properly. This is because the individual ingredients still had not been added to the input interface as assigned in Sprint 1. While MySql would catch this mis-match and violation of the Recipe table schema, Firebase (a "noSql" database) allows for the input of the non-fitting criteria from the interface but cannot then utilize those recipes added as they don't "fit" into what is queried for display later.
